---
# roles/unattended_upgrades/tasks/unattended-upgrades.yml

- name: Install unattended-upgrades
  ansible.builtin.apt:
    pkg: unattended-upgrades
    state: present
    update_cache: true

- name: Deploy 20auto-upgrades configuration
  ansible.builtin.template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'

- name: Enable remove unused dependencies in 50unattended-upgrades
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^//?Unattended-Upgrade::Remove-Unused-Dependencies'
    line: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'
    create: true
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'

- name: Ensure "-updates" origin is enabled in 50unattended-upgrades
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^//?\s*"\$\{distro_id\}:\$\{distro_codename\}-updates";'
    line: '        "${distro_id}:${distro_codename}-updates";'
    insertafter: '^Unattended-Upgrade::Allowed-Origins\s*{'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
    state: present

- name: Ensure apt-daily-upgrade.timer is enabled
  ansible.builtin.systemd:
    name: apt-daily-upgrade.timer
    enabled: true
    state: started
